main: me.wand555.Challenge.Challenge.Challenge
name: Challenge
version: 0.0.3
description: Test.
api-version: 1.13
author: wand555
commands:
  challenge:
    usage: /challenge <option>
    description: sdfgsg
    permission: challenge.create
    message: &cYou dont have permission to set a campfire!
  timer:
    usage: /timer <option>
    description: timer settings
  hp:
    usage: /hp <player> <amount>
    description: Sets the player's HP to the given amount.
  settings:
    usage: /settings
    description: Opens gui with settings.
    